export const DOWNLOAD_ONLY_OVER_WIFI_KEY = 'DOWNLOAD_ONLY_OVER_WIFI_KEY';
export const PUSH_NOTIFICATION_KEY = 'PUSH_NOTIFICATION_KEY';
export const LIMIT_EARN_COINS_TIME = 5 * 60 * 1000;
export const LAST_EARN_COINS_TIME = 'LAST_EARN_COINS_TIME';
export const MODE_KEY = 'MODE_KEY';
export const FISRT_USEAPP_KEY = 'FISRT_USEAPP_KEY';
